apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: data-tokensync-test-job
  namespace: dev
spec:
  template:
    metadata:
      name: data-tokensync-test-job
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl"]
        args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      # Do not restart containers after they exit
      restartPolicy: Never
  # of retries before marking as failed.
  backoffLimit: 4

